spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: market_db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kafka:
  host: localhost
  port: 29092
  topic: market-api-topic
